// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnDP8j0evckd4L4EjWaq9bxrS5C2Vi4I',
    appId: '1:177050153144:web:0d596bd54bfdd1b11ac44d',
    messagingSenderId: '177050153144',
    projectId: 'md2022-96ac9',
    authDomain: 'md2022-96ac9.firebaseapp.com',
    storageBucket: 'md2022-96ac9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzopRyArSZw68bRSZUljTHuk73aRkmcg',
    appId: '1:177050153144:android:387ecb25810318971ac44d',
    messagingSenderId: '177050153144',
    projectId: 'md2022-96ac9',
    storageBucket: 'md2022-96ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaQdNlt5hz1U50S0pNlfv_FZhx3efwYM',
    appId: '1:177050153144:ios:5ab07c9cb7caa8851ac44d',
    messagingSenderId: '177050153144',
    projectId: 'md2022-96ac9',
    storageBucket: 'md2022-96ac9.appspot.com',
    iosClientId: '177050153144-h8i8tjp34iv1c0bc8lcfe5furha4he13.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamesScore',
  );
}
